### ISSUE TITLE
Aprender Kivy

### ISSUE THREAD

**Issue by Shinkei** [Shinkei/wormholeUI#1]
Aprender Kivi

**Comment by Ondama** [comment]
Partes importantes de la documentación:
https://kivy.org/docs/guide/events.html
https://kivy.org/docs/guide/widgets.html
https://kivy.org/docs/guide/lang.html#designing-with-the-kivy-language
https://kivy.org/docs/guide/other-frameworks.html
https://kivy.org/docs/guide/basic.html
